== GTS to WIS2 Gateway
The Executive Council, with resolution 34 (EC-76), endorsed the WMO Information System 2.0 (WIS 2.0) implementation plan and recognized the importance of establishing a pilot phase to develop the WIS 2.0 infrastructure and begin testing it in order to be ready for a preoperational phase in 2024, and then for the transition starting on 2025. According to the WIS 2.0 implementation plan, the Global Telecommunication System (GTS) will be decommissioned by 2030, and National Meteorological and Hydrological Services NMHSs will use the WIS 2.0 platform for data exchange.
During the transition period, in order to avoid some WIS centres being forced to run both data-sharing frameworks simultaneously WIS 2.0 and GTS, with the challenges associated with maintaining two operational systems for the same purpose, a gatewy from GTS to WIS2 is designed, taking into account the time required for Members to migrate to the new systems and minimizing the time a member has to operate both systems in parallel.

=== Purpose
The purpose of this gateway is to enable members who migrate to WIS2 and stoped their GTS systems to continue receiving GTS data from WIS2. It enables users also who are not connected to GTS to access GTS data, during the transition phase, from WIS2.

=== GTS to WIS2 Gateway provider
The gateway will be provided by Germany's National Meteorological Service (DWD). The Japanese Meteorological Agency (JMA) may provide a second gateway for more sustainability and resilience.
 
=== Technical requirements
* GTS headers shall be used in the Topic Hierarchy (TH)
*	The TH for GTS data on the Global Cache (GC) shall be as follows: 
** cache/a/wis2/xxg/gts_to_wis2_GC-name/TTAAii
** e.g for DWD: cache/a/wis2/xxg/gts_to_wis2_dwd/TTAAii

